### ISSUE TITLE
Unable to run iperf

### ISSUE THREAD

**Issue by charming47** [gramorgan/mininet-fat-tree#1]
I'm trying to run `sudo ./run_net.py dijkstra --iperf`

But I got this:

```
POX 0.7.0 (gar) / Copyright 2011-2020 James McCauley, et al.
WARNING:version:Support for Python 3 is experimental.
INFO:core:POX 0.7.0 (gar) is up.
Unable to contact the remote controller at 127.0.0.1:6653
Unable to contact the remote controller at 127.0.0.1:6633
Setting remote controller to 127.0.0.1:6653
running iperf test
using controller  dijkstra
Traceback (most recent call last):
  File "./run_net.py", line 146, in <module>
    run_iperf(net, infile)
  File "./run_net.py", line 96, in run_iperf
    results.append(int(iperf_output[8]))
IndexError: list index out of range
```

Then I print the result of `iperf_output`,
and I got this:  `[' ']` (a list with a empty string)

I'm trying to figure out the problem, I add a line of code in the function of `run_iperf`:
```
for p in client_procs:
	p.wait()
	print p.communicate()[0]
	iperf_output = p.communicate()[0].split(',')
	results.append(int(iperf_output[8]))
```

But I got another problem:
```
POX 0.7.0 (gar) / Copyright 2011-2020 James McCauley, et al.
WARNING:version:Support for Python 3 is experimental.
INFO:core:POX 0.7.0 (gar) is up.
Unable to contact the remote controller at 127.0.0.1:6653
Unable to contact the remote controller at 127.0.0.1:6633
Setting remote controller to 127.0.0.1:6653
running iperf test
using controller  dijkstra


Traceback (most recent call last):
  File "./run_net.py", line 148, in <module>
    run_iperf(net, infile)
  File "./run_net.py", line 97, in run_iperf
    iperf_output = p.communicate()[0].split(',')
  File "/usr/lib/python2.7/subprocess.py", line 483, in communicate
    return self._communicate(input)
  File "/usr/lib/python2.7/subprocess.py", line 1124, in _communicate
    stdout, stderr = self._communicate_with_poll(input)
  File "/usr/lib/python2.7/subprocess.py", line 1169, in _communicate_with_poll
    register_and_append(self.stdout, select_POLLIN_POLLPRI)
  File "/usr/lib/python2.7/subprocess.py", line 1156, in register_and_append
    poller.register(file_obj.fileno(), eventmask)
ValueError: I/O operation on closed file
```
Now I don't know what to do next.

**Comment by charming47** [comment]
Well...I work it out. I should copy `fakearp.py`, `controller_dj.py`, `controller_2level.py` and  `topo_ft.py` to `~\pox\pox\`
